<?php

namespace XcVm\Domain\Cluster;

use XcVm\Core\Config\SettingsManager;
use XcVm\Infrastructure\Database\DatabaseAware;

/**
 * MAIN's nginx config for the cluster API (plan §3, "Transport" and
 * "Endpoints and HTTPS"), rendered from the code and the settings instead of
 * fixed in nginx.conf. All of it is MAIN only: the LB build strips
 * Domain/Cluster and cluster_locations.conf, and the LB nginx has no route.
 *
 * | File (bin/nginx/conf/) | Included by | Holds |
 * | --- | --- | --- |
 * | `cluster_locations.conf` | the public `server{}`, and each server below | `location ^~ /cluster/v1/`, lanes from ClusterPool::INGEST_OPS |
 * | `cluster.d/listen.conf` | `http{}` | a plain-HTTP server on `cluster_api_port`, when it is not 0 |
 * | `cluster.d/old_port.conf` | `http{}` | a server per old port ClusterEndpoint keeps for 7 days |
 *
 * The location applies the plan's transport limits: 100 r/s per TCP peer
 * (zone `cluster` in nginx.conf, keyed by `$realip_remote_addr`), burst 400,
 * status 429, `client_max_body_size 8m`, `gzip off`. nginx's own 429, 413,
 * 502, 504 and 404 carry no MAC, and agents treat them as transport errors.
 *
 * The public server keeps the location whatever `cluster_api_port` says: the
 * HTTPS URLs in the policy use it, and it keeps the broadcast port's URL
 * working for a node that has not moved to the dedicated port yet.
 *
 * apply() writes what changed atomically, runs `nginx -t` and, when it
 * fails, puts every file back as it was; otherwise it reloads nginx. Neither
 * says whether nginx can take a port: `nginx -t` passes when another program
 * holds it (in test mode nginx skips EADDRINUSE), and `nginx -s reload` exits
 * 0 once the signal is sent, while the master keeps its previous config when
 * the bind fails, and the next start fails outright. So a dedicated port that
 * nginx does not listen on yet must be free before anything is written, and
 * nginx must serve it after the reload, or the previous files go back.
 *
 * It runs only as the user nginx runs as (xc_vm): the files live in a
 * directory that user owns, and root would follow a link planted there.
 * `status` (root) and the root set_port handler run it through
 * `cluster:nginx` as xc_vm; cron:cluster runs it every minute, which retries
 * a render that failed and undoes one that raced a settings save.
 */
final class ClusterNginxConfig {
	use DatabaseAware;

	public const LOCATIONS = 'cluster_locations.conf';

	public const LISTEN = 'cluster.d/listen.conf';

	public const OLD_PORT = 'cluster.d/old_port.conf';

	/** ClusterEndpoint's file before this class; an nginx.conf that includes cluster.d/ no longer reads it. */
	public const RETIRED = 'cluster_legacy.conf';

	/** The plan's burst per TCP peer; the rate (100 r/s) is the `cluster` zone's, in nginx.conf. */
	public const BURST = 400;

	private const CONF_DIR = 'bin/nginx/conf/';

	/** The last refusal audited, so a render retried every minute audits it once. */
	private const REFUSED = 'cluster.d/.refused';

	/** How long nginx gets to serve a new port after the reload; its own bind retries last 2.5 s. */
	private const SERVE_WAIT_MS = 3000;

	private static ?string $rBase = null;

	private static string $rUser = 'xc_vm';

	private static ?\Closure $rRunner = null;

	private static ?\Closure $rProbe = null;

	/** Tests: another install root (null: MAIN_HOME), and the user nginx runs as. */
	public static function useBase(?string $rBase, string $rUser = 'xc_vm'): void {
		self::$rBase = $rBase;
		self::$rUser = $rUser;
	}

	/** Tests: run nginx with fn(list<string> $rArgv): array{0: int, 1: string} (null: the real one). */
	public static function useRunner(?\Closure $rRunner): void {
		self::$rRunner = $rRunner;
	}

	/**
	 * Tests: check a port with fn(string $rCheck, int $rPort): bool (null: the
	 * real checks). $rCheck is 'free' (nothing listens on it, so nginx can
	 * bind it) or 'serving' (nginx took it after the reload).
	 */
	public static function useProbe(?\Closure $rProbe): void {
		self::$rProbe = $rProbe;
	}

	/** The /cluster/v1/ location: control ops on cluster_ctl, ingest ops on cluster_ingest. */
	public static function locations(): string {
		return "# Generated by XC_VM (ClusterNginxConfig): the cluster API, included by the\n"
			. "# public server{} and by the servers in cluster.d/. MAIN only. Do not edit.\n"
			. "# Control ops (the agent's poll and ctl lanes) run on the cluster_ctl pool,\n"
			. "# ingest ops (its p0 and bulk lanes) on cluster_ingest; the nested location\n"
			. "# inherits the rest. nginx's own 429, 413, 502, 504 and 404 carry no MAC:\n"
			. "# agents treat them as transport errors.\n"
			. "location ^~ /cluster/v1/ {\n"
			. '    limit_req zone=cluster burst=' . self::BURST . " nodelay;\n"
			. "    limit_req_status 429;\n"
			. "    client_max_body_size 8m;\n"
			. "    gzip off;\n"
			. "    fastcgi_pass cluster_ctl;\n"
			. "    include fastcgi_params;\n"
			. "    fastcgi_buffering on;\n"
			. "    fastcgi_keep_conn on;\n"
			. "    fastcgi_param SCRIPT_FILENAME /home/xc_vm/Public/cluster/index.php;\n"
			. "    fastcgi_param SCRIPT_NAME /public/cluster/index.php;\n"
			. "\n"
			. '    location ~ ^/cluster/v1/(' . implode('|', ClusterPool::INGEST_OPS) . ")$ {\n"
			. "        fastcgi_pass cluster_ingest;\n"
			. "    }\n"
			. "}\n";
	}

	/**
	 * What each file should hold: path under bin/nginx/conf/ => content, or
	 * null when the file should not exist.
	 *
	 * @param array<string, mixed> $rSettings
	 * @param list<int> $rServed The ports the public server listens on (servedPorts()).
	 * @return array<string, ?string>
	 */
	public static function render(array $rSettings, array $rServed, ?int $rNow = null): array {
		$rServed = array_map('intval', $rServed);
		$rApiPort = (int) ($rSettings['cluster_api_port'] ?? 0);
		$rListen = null;
		if ($rApiPort >= 1 && $rApiPort <= 65535 && !in_array($rApiPort, $rServed, true)) {
			$rListen = "# Generated by XC_VM (ClusterNginxConfig): the cluster API's own plain-HTTP\n"
				. "# port (cluster_api_port). It serves /cluster/v1/ and nothing else. Do not edit.\n"
				. self::server($rApiPort, null);
			$rServed[] = $rApiPort;
		}
		$rOld = '';
		foreach (ClusterEndpoint::legacyPorts($rSettings, $rNow) as $rPort => $rUntil) {
			if (!in_array((int) $rPort, $rServed, true)) {
				$rOld .= self::server((int) $rPort, (int) $rUntil);
			}
		}
		return [
			self::LOCATIONS => self::locations(),
			self::LISTEN => $rListen,
			self::OLD_PORT => $rOld === '' ? null : "# Generated by XC_VM (ClusterNginxConfig): MAIN's old cluster API ports, kept\n"
				. "# for the cluster API alone until nodes have moved (ClusterEndpoint). Do not edit.\n" . $rOld,
		];
	}

	/**
	 * The ports MAIN's public server listens on, from its ports/ includes.
	 *
	 * @return list<int>
	 */
	public static function servedPorts(string $rConfDir): array {
		return self::ports((string) @file_get_contents($rConfDir . 'ports/http.conf') . "\n" . (string) @file_get_contents($rConfDir . 'ports/https.conf'));
	}

	/**
	 * A settings save that changes `cluster_api_port` from $rOld to $rNew
	 * (plan §3: refused on port collisions, applied only once `nginx -t`
	 * passes). nginx gets the new port, and keeps the old one for the nodes
	 * (ClusterEndpoint), before the value is stored. Returns null when the
	 * port stays. Otherwise `refused` is null when nginx serves the new port,
	 * or the translation key of the refusal, with every file as it was:
	 * cluster_error_port_busy (another program listens on the port) or
	 * cluster_error_nginx (nginx refused it, or did not serve it after the
	 * reload; `error` holds its words). `record` is for commitApiPort().
	 *
	 * @param array<string, mixed> $rCurrent The stored settings.
	 * @param array<string, mixed> $rMain The main server's `servers` row.
	 * @return array{refused: ?string, error: string, record: array{0: int, 1: int, 2: array<string, mixed>, 3: array<string, mixed>}}|null
	 */
	public static function stageApiPort(int $rOld, int $rNew, array $rCurrent, array $rMain): ?array {
		if ($rOld === $rNew) {
			return null;
		}
		$rOut = ['refused' => null, 'error' => '', 'record' => [$rOld, $rNew, $rCurrent, $rMain]];
		if ($rNew > 0 && self::portBusy($rNew)) {
			$rOut['refused'] = 'cluster_error_port_busy';
			return $rOut;
		}
		$rKept = ClusterEndpoint::afterApiPortChange($rOld, $rNew, $rCurrent, $rMain) ?? ClusterEndpoint::legacyPorts($rCurrent);
		$rResult = self::apply(['cluster_api_port' => $rNew, 'cluster_legacy_ports' => (string) json_encode($rKept)] + $rCurrent);
		if (!$rResult['ok']) {
			$rOut['refused'] = 'cluster_error_nginx';
			$rOut['error'] = $rResult['error'];
		}
		return $rOut;
	}

	/**
	 * After the settings UPDATE of a port stageApiPort() staged: once it is
	 * stored ($rStored), the nodes move to it (ClusterEndpoint::
	 * recordApiPortChange()). Either way nginx is rendered again from what
	 * is stored: that undoes a render from the old value that ran in between
	 * (status, set_port, cron:cluster), and a save that failed puts nginx
	 * back on the stored port.
	 *
	 * @param array{refused: ?string, error: string, record: array{0: int, 1: int, 2: array<string, mixed>, 3: array<string, mixed>}} $rStage
	 * @return array{ok: bool, changed: bool, reloaded: bool, error: string} apply()'s result
	 */
	public static function commitApiPort(array $rStage, bool $rStored): array {
		if ($rStored && $rStage['refused'] === null) {
			ClusterEndpoint::recordApiPortChange(...$rStage['record']);
		}
		return self::apply();
	}

	/**
	 * Render from the settings (null: the stored ones), write what changed,
	 * and keep it only once `nginx -t` passes; then reload nginx when asked.
	 * Returns ok (false when it was refused, and every file is then as it
	 * was), changed (a file differs now), reloaded and the error.
	 *
	 * Refused: nginx.conf does not read cluster.d/ while the render needs
	 * it, a new dedicated port is taken by another program, it could not be
	 * written, `nginx -t` failed, or, on a reload, nginx did not serve the new
	 * dedicated port.
	 *
	 * @param array<string, mixed>|null $rSettings
	 * @return array{ok: bool, changed: bool, reloaded: bool, error: string}
	 */
	public static function apply(?array $rSettings = null, bool $rReload = true): array {
		$rOut = ['ok' => false, 'changed' => false, 'reloaded' => false, 'error' => ''];
		$rBase = self::base();
		if ($rBase === null || !self::runsAsNginxUser()) {
			$rOut['error'] = 'not run as ' . self::$rUser;
			return $rOut;
		}
		$rConf = $rBase . self::CONF_DIR;
		if (!is_dir($rConf . 'cluster.d') && !@mkdir($rConf . 'cluster.d', 0755, true)) {
			$rOut['error'] = 'cannot create ' . $rConf . 'cluster.d';
			return $rOut;
		}
		$rLock = @fopen($rConf . 'cluster.d/.lock', 'c');
		if ($rLock !== false) {
			flock($rLock, LOCK_EX);
		}
		try {
			return self::applyLocked($rConf, $rSettings ?? self::stored(), $rReload);
		} finally {
			if ($rLock !== false) {
				flock($rLock, LOCK_UN);
				fclose($rLock);
			}
		}
	}

	/**
	 * @param array<string, mixed> $rSettings
	 * @return array{ok: bool, changed: bool, reloaded: bool, error: string}
	 */
	private static function applyLocked(string $rConf, array $rSettings, bool $rReload): array {
		$rOut = ['ok' => false, 'changed' => false, 'reloaded' => false, 'error' => ''];
		$rWanted = self::render($rSettings, self::servedPorts($rConf));
		if (preg_match('#^\s*include\s+cluster\.d/#m', (string) @file_get_contents($rConf . 'nginx.conf'))) {
			$rWanted[self::RETIRED] = null;
		} elseif ($rWanted[self::LISTEN] !== null || $rWanted[self::OLD_PORT] !== null) {
			// An nginx.conf from before (an update rolled back one that failed
			// nginx -t) reads neither file: nginx -t would pass, and a port
			// the nodes are sent to would never be served.
			$rOut['error'] = 'nginx.conf predates the rendered cluster config (no include cluster.d/*.conf): it cannot serve cluster_api_port or an old port';
			self::refused($rConf, ['error' => $rOut['error']]);
			return $rOut;
		}
		// The dedicated port, when nginx does not listen on it yet.
		$rNewPort = $rWanted[self::LISTEN] === null ? null : (int) $rSettings['cluster_api_port'];
		if ($rNewPort !== null && in_array($rNewPort, self::listened($rConf), true)) {
			$rNewPort = null;
		}
		if ($rNewPort !== null && !self::probe('free', $rNewPort)) {
			$rOut['error'] = 'port ' . $rNewPort . ' is in use by another program';
			self::refused($rConf, ['error' => $rOut['error']]);
			return $rOut;
		}
		// file => what it held (null: it did not exist), for each file written.
		$rBefore = [];
		foreach ($rWanted as $rFile => $rContent) {
			$rOld = is_file($rConf . $rFile) ? (string) file_get_contents($rConf . $rFile) : null;
			if ($rOld === $rContent) {
				continue;
			}
			$rBefore[$rFile] = $rOld;
			if (!self::put($rConf . $rFile, $rContent)) {
				self::restore($rConf, $rBefore);
				$rOut['error'] = 'cannot write ' . $rConf . $rFile;
				return $rOut;
			}
		}
		if ($rBefore === []) {
			@unlink($rConf . self::REFUSED);
			$rOut['ok'] = true;
			return $rOut;
		}

		$rBin = dirname($rConf) . '/sbin/nginx';
		[$rCode, $rText] = self::run([$rBin, '-t', '-c', $rConf . 'nginx.conf']);
		if ($rCode !== 0) {
			self::restore($rConf, $rBefore);
			$rOut['error'] = trim($rText) !== '' ? trim($rText) : 'nginx -t failed (' . $rCode . ')';
			self::refused($rConf, ['files' => array_keys($rBefore), 'error' => $rOut['error']]);
			return $rOut;
		}
		if ($rReload) {
			$rSignal = [$rBin, '-s', 'reload', '-c', $rConf . 'nginx.conf'];
			$rOut['reloaded'] = self::run($rSignal)[0] === 0;
			// The exit code says only that the signal was sent: the master binds
			// a new port afterwards, and keeps its previous config when it cannot.
			if ($rNewPort !== null && !($rOut['reloaded'] && self::probe('serving', $rNewPort))) {
				self::restore($rConf, $rBefore);
				self::run($rSignal);
				$rOut['reloaded'] = false;
				$rOut['error'] = 'nginx did not serve port ' . $rNewPort . ' after the reload (another program took it, or nginx is not running)';
				self::refused($rConf, ['files' => array_keys($rBefore), 'error' => $rOut['error']]);
				return $rOut;
			}
		}
		@unlink($rConf . self::REFUSED);
		$rOut['ok'] = true;
		$rOut['changed'] = true;
		ClusterAudit::log('cluster.nginx', null, ['ok' => true, 'files' => array_keys($rBefore), 'api_port' => (int) ($rSettings['cluster_api_port'] ?? 0)], 'system');
		return $rOut;
	}

	/**
	 * The stored settings, with the two the render reads read again from the
	 * database: a settings save stores them after this process loaded its own.
	 *
	 * @return array<string, mixed>
	 */
	private static function stored(): array {
		$rSettings = SettingsManager::getAll();
		try {
			$rDb = self::db();
			if ($rDb->query('SELECT `cluster_api_port`, `cluster_legacy_ports` FROM `settings` LIMIT 1;')) {
				$rRow = $rDb->get_row();
				if (is_array($rRow) && $rRow !== []) {
					$rSettings = $rRow + $rSettings;
				}
			}
		} catch (\Throwable) {
			// The loaded settings, then.
		}
		return $rSettings;
	}

	/**
	 * Audit a refusal once: a render retried every minute (cron:cluster)
	 * fails the same way until someone fixes what nginx names.
	 *
	 * @param array<string, mixed> $rDetail
	 */
	private static function refused(string $rConf, array $rDetail): void {
		$rDetail = ['ok' => false] + $rDetail;
		$rDetail['error'] = substr((string) $rDetail['error'], 0, 500);
		$rKey = md5((string) json_encode($rDetail));
		if (@file_get_contents($rConf . self::REFUSED) === $rKey) {
			return;
		}
		@file_put_contents($rConf . self::REFUSED, $rKey);
		ClusterAudit::log('cluster.nginx', null, $rDetail, 'system');
	}

	/** Whether another program listens on $rPort: nginx does not, by its files, and it cannot be bound. */
	private static function portBusy(int $rPort): bool {
		$rBase = self::base();
		return $rBase !== null && !in_array($rPort, self::listened($rBase . self::CONF_DIR), true) && !self::probe('free', $rPort);
	}

	/**
	 * The ports nginx listens on by its files: the public server's, the
	 * dedicated port's and the old ports'.
	 *
	 * @return list<int>
	 */
	private static function listened(string $rConf): array {
		$rText = '';
		foreach (['ports/http.conf', 'ports/https.conf', self::LISTEN, self::OLD_PORT] as $rFile) {
			$rText .= (string) @file_get_contents($rConf . $rFile) . "\n";
		}
		return self::ports($rText);
	}

	/**
	 * The ports of the `listen` directives in $rText, sorted.
	 *
	 * @return list<int>
	 */
	private static function ports(string $rText): array {
		$rPorts = [];
		if (preg_match_all('/\blisten\s+(?:\S*:)?(\d{1,5})\b/', $rText, $rMatches)) {
			$rPorts = array_map('intval', $rMatches[1]);
		}
		$rPorts = array_values(array_unique($rPorts));
		sort($rPorts);
		return $rPorts;
	}

	/**
	 * 'free': nothing listens on $rPort, so nginx can bind it (the address
	 * `listen <port>;` binds). 'serving': something accepts on it within
	 * SERVE_WAIT_MS; after a reload, with the port free before, that is nginx.
	 */
	private static function probe(string $rCheck, int $rPort): bool {
		if (self::$rProbe !== null) {
			return (bool) (self::$rProbe)($rCheck, $rPort);
		}
		if ($rCheck === 'free') {
			$rSocket = @stream_socket_server('tcp://0.0.0.0:' . $rPort, $rErrNo, $rErrStr);
			if ($rSocket === false) {
				return false;
			}
			fclose($rSocket);
			return true;
		}
		$rUntil = microtime(true) + self::SERVE_WAIT_MS / 1000;
		do {
			$rSocket = @stream_socket_client('tcp://127.0.0.1:' . $rPort, $rErrNo, $rErrStr, 0.5);
			if ($rSocket !== false) {
				fclose($rSocket);
				return true;
			}
			usleep(100000);
		} while (microtime(true) < $rUntil);
		return false;
	}

	/** One server{} for the cluster API alone on $rPort; $rUntil names an old port's expiry. */
	private static function server(int $rPort, ?int $rUntil): string {
		return "server {\n"
			. '    listen ' . $rPort . ";\n"
			. ($rUntil === null ? '' : '    # until ' . gmdate('Y-m-d H:i', $rUntil) . " UTC\n")
			. "    server_tokens off;\n"
			. "    include cluster_locations.conf;\n"
			. "    location / {\n"
			. "        return 404;\n"
			. "    }\n"
			. "}\n";
	}

	/** Write $rContent atomically (null: remove the file). */
	private static function put(string $rPath, ?string $rContent): bool {
		if ($rContent === null) {
			return !file_exists($rPath) || @unlink($rPath);
		}
		$rTmp = $rPath . '.tmp';
		if (@file_put_contents($rTmp, $rContent) === false || !@rename($rTmp, $rPath)) {
			@unlink($rTmp);
			return false;
		}
		@chmod($rPath, 0644);
		return true;
	}

	/** @param array<string, ?string> $rBefore */
	private static function restore(string $rConf, array $rBefore): void {
		foreach ($rBefore as $rFile => $rContent) {
			self::put($rConf . $rFile, $rContent);
		}
	}

	/**
	 * @param list<string> $rArgv
	 * @return array{0: int, 1: string} exit code, output
	 */
	private static function run(array $rArgv): array {
		if (self::$rRunner !== null) {
			$rResult = (self::$rRunner)($rArgv);
			return [(int) ($rResult[0] ?? 1), (string) ($rResult[1] ?? '')];
		}
		if (!is_executable($rArgv[0])) {
			return [127, $rArgv[0] . ' is not executable'];
		}
		$rProc = proc_open($rArgv, [0 => ['file', '/dev/null', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $rPipes);
		if (!is_resource($rProc)) {
			return [127, 'cannot run ' . $rArgv[0]];
		}
		// A few lines at most (nginx -t reports on stderr), far below a pipe's buffer.
		$rText = (string) stream_get_contents($rPipes[1]) . (string) stream_get_contents($rPipes[2]);
		fclose($rPipes[1]);
		fclose($rPipes[2]);
		return [proc_close($rProc), $rText];
	}

	private static function runsAsNginxUser(): bool {
		$rUser = function_exists('posix_getpwuid') ? posix_getpwuid(posix_geteuid()) : false;
		return is_array($rUser) && $rUser['name'] === self::$rUser;
	}

	private static function base(): ?string {
		return self::$rBase ?? (defined('MAIN_HOME') ? (string) MAIN_HOME : null);
	}
}
