<?php

namespace XcVm\Domain\Cluster;

use XcVm\Core\Config\SettingsManager;

/**
 * MAIN's nginx config for the cluster API (plan §3, "Transport" and
 * "Endpoints and HTTPS"), rendered from the code and the settings instead of
 * fixed in nginx.conf. All of it is MAIN only: the LB build strips
 * Domain/Cluster and cluster_locations.conf, and the LB nginx has no route.
 *
 * | File (bin/nginx/conf/) | Included by | Holds |
 * | --- | --- | --- |
 * | `cluster_locations.conf` | the public `server{}`, and each server below | `location ^~ /cluster/v1/`, lanes from ClusterPool::INGEST_OPS |
 * | `cluster.d/listen.conf` | `http{}` | a plain-HTTP server on `cluster_api_port`, when it is not 0 |
 * | `cluster.d/old_port.conf` | `http{}` | a server per old port ClusterEndpoint keeps for 7 days |
 *
 * The location applies the plan's transport limits: 100 r/s per TCP peer
 * (zone `cluster` in nginx.conf, keyed by `$realip_remote_addr`), burst 400,
 * status 429, `client_max_body_size 8m`, `gzip off`. nginx's own 429, 413,
 * 502, 504 and 404 carry no MAC, and agents treat them as transport errors.
 *
 * The public server keeps the location whatever `cluster_api_port` says: the
 * HTTPS URLs in the policy use it, and it keeps the broadcast port's URL
 * working for a node that has not moved to the dedicated port yet.
 *
 * apply() writes what changed atomically, runs `nginx -t` and, when it
 * fails, puts every file back as it was; otherwise it reloads nginx. It runs
 * only as the user nginx runs as (xc_vm): the files live in a directory that
 * user owns, and root would follow a link planted there. `status` (root)
 * and the root set_port handler run it through `cluster:nginx` as xc_vm.
 */
final class ClusterNginxConfig {
	public const LOCATIONS = 'cluster_locations.conf';

	public const LISTEN = 'cluster.d/listen.conf';

	public const OLD_PORT = 'cluster.d/old_port.conf';

	/** ClusterEndpoint's file before this class; an nginx.conf that includes cluster.d/ no longer reads it. */
	public const RETIRED = 'cluster_legacy.conf';

	/** The plan's burst per TCP peer; the rate (100 r/s) is the `cluster` zone's, in nginx.conf. */
	public const BURST = 400;

	private const CONF_DIR = 'bin/nginx/conf/';

	private static ?string $rBase = null;

	private static string $rUser = 'xc_vm';

	private static ?\Closure $rRunner = null;

	/** Tests: another install root (null: MAIN_HOME), and the user nginx runs as. */
	public static function useBase(?string $rBase, string $rUser = 'xc_vm'): void {
		self::$rBase = $rBase;
		self::$rUser = $rUser;
	}

	/** Tests: run nginx with fn(list<string> $rArgv): array{0: int, 1: string} (null: the real one). */
	public static function useRunner(?\Closure $rRunner): void {
		self::$rRunner = $rRunner;
	}

	/** The /cluster/v1/ location: control ops on cluster_ctl, ingest ops on cluster_ingest. */
	public static function locations(): string {
		return "# Generated by XC_VM (ClusterNginxConfig): the cluster API, included by the\n"
			. "# public server{} and by the servers in cluster.d/. MAIN only. Do not edit.\n"
			. "# Control ops (the agent's poll and ctl lanes) run on the cluster_ctl pool,\n"
			. "# ingest ops (its p0 and bulk lanes) on cluster_ingest; the nested location\n"
			. "# inherits the rest. nginx's own 429, 413, 502, 504 and 404 carry no MAC:\n"
			. "# agents treat them as transport errors.\n"
			. "location ^~ /cluster/v1/ {\n"
			. '    limit_req zone=cluster burst=' . self::BURST . " nodelay;\n"
			. "    limit_req_status 429;\n"
			. "    client_max_body_size 8m;\n"
			. "    gzip off;\n"
			. "    fastcgi_pass cluster_ctl;\n"
			. "    include fastcgi_params;\n"
			. "    fastcgi_buffering on;\n"
			. "    fastcgi_keep_conn on;\n"
			. "    fastcgi_param SCRIPT_FILENAME /home/xc_vm/Public/cluster/index.php;\n"
			. "    fastcgi_param SCRIPT_NAME /public/cluster/index.php;\n"
			. "\n"
			. '    location ~ ^/cluster/v1/(' . implode('|', ClusterPool::INGEST_OPS) . ")$ {\n"
			. "        fastcgi_pass cluster_ingest;\n"
			. "    }\n"
			. "}\n";
	}

	/**
	 * What each file should hold: path under bin/nginx/conf/ => content, or
	 * null when the file should not exist.
	 *
	 * @param array<string, mixed> $rSettings
	 * @param list<int> $rServed The ports the public server listens on (servedPorts()).
	 * @return array<string, ?string>
	 */
	public static function render(array $rSettings, array $rServed, ?int $rNow = null): array {
		$rServed = array_map('intval', $rServed);
		$rApiPort = (int) ($rSettings['cluster_api_port'] ?? 0);
		$rListen = null;
		if ($rApiPort >= 1 && $rApiPort <= 65535 && !in_array($rApiPort, $rServed, true)) {
			$rListen = "# Generated by XC_VM (ClusterNginxConfig): the cluster API's own plain-HTTP\n"
				. "# port (cluster_api_port). It serves /cluster/v1/ and nothing else. Do not edit.\n"
				. self::server($rApiPort, null);
			$rServed[] = $rApiPort;
		}
		$rOld = '';
		foreach (ClusterEndpoint::legacyPorts($rSettings, $rNow) as $rPort => $rUntil) {
			if (!in_array((int) $rPort, $rServed, true)) {
				$rOld .= self::server((int) $rPort, (int) $rUntil);
			}
		}
		return [
			self::LOCATIONS => self::locations(),
			self::LISTEN => $rListen,
			self::OLD_PORT => $rOld === '' ? null : "# Generated by XC_VM (ClusterNginxConfig): MAIN's old cluster API ports, kept\n"
				. "# for the cluster API alone until nodes have moved (ClusterEndpoint). Do not edit.\n" . $rOld,
		];
	}

	/**
	 * The ports MAIN's public server listens on, from its ports/ includes.
	 *
	 * @return list<int>
	 */
	public static function servedPorts(string $rConfDir): array {
		$rPorts = [];
		foreach (['http', 'https'] as $rType) {
			$rText = @file_get_contents($rConfDir . 'ports/' . $rType . '.conf');
			if (is_string($rText) && preg_match_all('/\blisten\s+(?:\S*:)?(\d{1,5})\b/', $rText, $rMatches)) {
				foreach ($rMatches[1] as $rPort) {
					$rPorts[] = (int) $rPort;
				}
			}
		}
		$rPorts = array_values(array_unique($rPorts));
		sort($rPorts);
		return $rPorts;
	}

	/**
	 * Render from the settings (null: the stored ones), write what changed,
	 * and keep it only once `nginx -t` passes; then reload nginx when asked.
	 * Returns ok (false when nginx refused it or it could not be written, and
	 * every file is then as it was), changed (a file differs now), reloaded
	 * and the error.
	 *
	 * @param array<string, mixed>|null $rSettings
	 * @return array{ok: bool, changed: bool, reloaded: bool, error: string}
	 */
	public static function apply(?array $rSettings = null, bool $rReload = true): array {
		$rOut = ['ok' => false, 'changed' => false, 'reloaded' => false, 'error' => ''];
		$rBase = self::base();
		if ($rBase === null || !self::runsAsNginxUser()) {
			$rOut['error'] = 'not run as ' . self::$rUser;
			return $rOut;
		}
		$rConf = $rBase . self::CONF_DIR;
		if (!is_dir($rConf . 'cluster.d') && !@mkdir($rConf . 'cluster.d', 0755, true)) {
			$rOut['error'] = 'cannot create ' . $rConf . 'cluster.d';
			return $rOut;
		}
		$rLock = @fopen($rConf . 'cluster.d/.lock', 'c');
		if ($rLock !== false) {
			flock($rLock, LOCK_EX);
		}
		try {
			return self::applyLocked($rConf, $rSettings ?? SettingsManager::getAll(), $rReload);
		} finally {
			if ($rLock !== false) {
				flock($rLock, LOCK_UN);
				fclose($rLock);
			}
		}
	}

	/**
	 * @param array<string, mixed> $rSettings
	 * @return array{ok: bool, changed: bool, reloaded: bool, error: string}
	 */
	private static function applyLocked(string $rConf, array $rSettings, bool $rReload): array {
		$rOut = ['ok' => false, 'changed' => false, 'reloaded' => false, 'error' => ''];
		$rWanted = self::render($rSettings, self::servedPorts($rConf));
		if (preg_match('#^\s*include\s+cluster\.d/#m', (string) @file_get_contents($rConf . 'nginx.conf'))) {
			$rWanted[self::RETIRED] = null;
		}
		// file => what it held (null: it did not exist), for each file written.
		$rBefore = [];
		foreach ($rWanted as $rFile => $rContent) {
			$rOld = is_file($rConf . $rFile) ? (string) file_get_contents($rConf . $rFile) : null;
			if ($rOld === $rContent) {
				continue;
			}
			$rBefore[$rFile] = $rOld;
			if (!self::put($rConf . $rFile, $rContent)) {
				self::restore($rConf, $rBefore);
				$rOut['error'] = 'cannot write ' . $rConf . $rFile;
				return $rOut;
			}
		}
		if ($rBefore === []) {
			$rOut['ok'] = true;
			return $rOut;
		}

		$rBin = dirname($rConf) . '/sbin/nginx';
		[$rCode, $rText] = self::run([$rBin, '-t', '-c', $rConf . 'nginx.conf']);
		if ($rCode !== 0) {
			self::restore($rConf, $rBefore);
			$rOut['error'] = trim($rText) !== '' ? trim($rText) : 'nginx -t failed (' . $rCode . ')';
			ClusterAudit::log('cluster.nginx', null, ['ok' => false, 'files' => array_keys($rBefore), 'error' => substr($rOut['error'], 0, 500)], 'system');
			return $rOut;
		}
		$rOut['ok'] = true;
		$rOut['changed'] = true;
		if ($rReload) {
			$rOut['reloaded'] = self::run([$rBin, '-s', 'reload', '-c', $rConf . 'nginx.conf'])[0] === 0;
		}
		ClusterAudit::log('cluster.nginx', null, ['ok' => true, 'files' => array_keys($rBefore), 'api_port' => (int) ($rSettings['cluster_api_port'] ?? 0)], 'system');
		return $rOut;
	}

	/** One server{} for the cluster API alone on $rPort; $rUntil names an old port's expiry. */
	private static function server(int $rPort, ?int $rUntil): string {
		return "server {\n"
			. '    listen ' . $rPort . ";\n"
			. ($rUntil === null ? '' : '    # until ' . gmdate('Y-m-d H:i', $rUntil) . " UTC\n")
			. "    server_tokens off;\n"
			. "    include cluster_locations.conf;\n"
			. "    location / {\n"
			. "        return 404;\n"
			. "    }\n"
			. "}\n";
	}

	/** Write $rContent atomically (null: remove the file). */
	private static function put(string $rPath, ?string $rContent): bool {
		if ($rContent === null) {
			return !file_exists($rPath) || @unlink($rPath);
		}
		$rTmp = $rPath . '.tmp';
		if (@file_put_contents($rTmp, $rContent) === false || !@rename($rTmp, $rPath)) {
			@unlink($rTmp);
			return false;
		}
		@chmod($rPath, 0644);
		return true;
	}

	/** @param array<string, ?string> $rBefore */
	private static function restore(string $rConf, array $rBefore): void {
		foreach ($rBefore as $rFile => $rContent) {
			self::put($rConf . $rFile, $rContent);
		}
	}

	/**
	 * @param list<string> $rArgv
	 * @return array{0: int, 1: string} exit code, output
	 */
	private static function run(array $rArgv): array {
		if (self::$rRunner !== null) {
			$rResult = (self::$rRunner)($rArgv);
			return [(int) ($rResult[0] ?? 1), (string) ($rResult[1] ?? '')];
		}
		if (!is_executable($rArgv[0])) {
			return [127, $rArgv[0] . ' is not executable'];
		}
		$rProc = proc_open($rArgv, [0 => ['file', '/dev/null', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $rPipes);
		if (!is_resource($rProc)) {
			return [127, 'cannot run ' . $rArgv[0]];
		}
		// A few lines at most (nginx -t reports on stderr), far below a pipe's buffer.
		$rText = (string) stream_get_contents($rPipes[1]) . (string) stream_get_contents($rPipes[2]);
		fclose($rPipes[1]);
		fclose($rPipes[2]);
		return [proc_close($rProc), $rText];
	}

	private static function runsAsNginxUser(): bool {
		$rUser = function_exists('posix_getpwuid') ? posix_getpwuid(posix_geteuid()) : false;
		return is_array($rUser) && $rUser['name'] === self::$rUser;
	}

	private static function base(): ?string {
		return self::$rBase ?? (defined('MAIN_HOME') ? (string) MAIN_HOME : null);
	}
}
